<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Modules\Users\Users.csproj" />
    <ProjectReference Include="..\Modules\Auth\Auth.csproj" />
    <ProjectReference Include="..\Modules\Events\Events.csproj" />
    <ProjectReference Include="..\Modules\Communities\Communities.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
